---
name: "GitHub Actions Demo"
on: 
 - push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "code/example-mec-app"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          isort-options: "-w 100"
